trustbloc/sidetree-core-go

pkg/dochandler/didvalidator/testdata/doc.json
pkg/dochandler/didvalidator/validator.go
pkg/dochandler/didvalidator/validator_test.go
pkg/dochandler/handler_test.go
pkg/document/diddocument.go
pkg/document/diddocument_test.go
pkg/document/publickey.go
pkg/document/publickey_test.go
pkg/document/service.go
pkg/document/service_test.go
pkg/document/testdata/invalid-lists.json
pkg/document/testdata/missing-info.json

Did document validator will check if document to be created conforms to Sidetree protocol specification for DID document creation. It also checks if update operation payload is valid: unique ID must be present and the original document with that ID exists in the document store.
Closes #15

feat: Did document validator

---

pkg/batch/filehandler/handler.go
pkg/dochandler/handler.go
pkg/document/diddocument.go
pkg/document/document.go
pkg/docutil/json.go
pkg/docutil/json_test.go
pkg/docutil/test_exports.go
pkg/observer/observer_test.go
pkg/processor/processor_test.go
scripts/unit.sh

Use a canonical JSON serializer in order to ensure that the fields of JSON documents are always serialized in the same way so that the hash of the document is deterministic.
closes #38

fix: Use a canonical JSON serializer

---

go.mod
pkg/batch/cutter/cutter.go
pkg/batch/cutter/cutter_test.go
pkg/batch/writer.go
pkg/batch/writer_test.go
pkg/mocks/cas.go

When a batch fails to be processed for whatever reason, the operations are returned to the head of the pending operations queue so that they may be processed at the next timeout.
closes #42

feat: Added handling of failed batch processing

---

.golangci.yml
pkg/docutil/json.go
pkg/observer/observer.go
pkg/observer/observer_test.go

Created a TxnProcessor struct which may be invoked externally.
Also fixed some golangci-lint errors due to the latest version of golangci-lint.
closes #45

feat: Publicly expose observer's txn processor

---

README.md
pkg/restapi/diddochandler/resolvehandler.go
pkg/restapi/diddochandler/resolvehandler_test.go
pkg/restapi/diddochandler/restapi_test.go
pkg/restapi/diddochandler/updatehandler.go
pkg/restapi/diddochandler/updatehandler_test.go

Add REST API endpoints according to the Sidetree spec for DID documents.
closes #54

feat: Implement Sidetree REST API for DID documents

---

.gitignore
Makefile
pkg/restapi/diddochandler/doc.go
pkg/restapi/diddochandler/resolvehandler.go
pkg/restapi/diddochandler/restapi_test.go
pkg/restapi/diddochandler/updatehandler.go
pkg/restapi/model/error.go
pkg/restapi/model/header.go
pkg/restapi/model/operation_type.go
pkg/restapi/model/request.go
pkg/restapi/model/response.go
scripts/generate-openapi-spec.sh

The OpenAPI spec is generated from the Sidetree model using swagger annotations.
closes #57

feat: Generate OpenAPI spec for the REST API

---

pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/restapi/diddochandler/doc.go

Add handling for DID with initial-values DID parameter during resolution
Standard resolution is performed if the DID is found to be registered on the blockchain.
If the DID Document cannot be found, the encoded DID Document given in the initial-values DID parameter is used to generate and return as the resolved DID Document, in which case the supplied encoded DID Document is subject to the same validation as an original DID Document in a create operation
Closes #67

feat: Support initial-values in DID Resolution

---

pkg/restapi/diddochandler/resolvehandler.go
pkg/restapi/diddochandler/resolvehandler_test.go
pkg/restapi/diddochandler/restapi_test.go
pkg/restapi/diddochandler/updatehandler.go
pkg/restapi/diddochandler/updatehandler_test.go

Added a configurable base path to the DID document handler.
closes #72

feat: Allow DID doc handler base path to be configurable

---

pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/docutil/doc.go
pkg/docutil/doc_test.go
pkg/restapi/diddochandler/restapi_test.go
pkg/restapi/diddochandler/updatehandler_test.go
pkg/restapi/dochandler/resolvehandler_test.go
pkg/restapi/dochandler/updatehandler.go
pkg/restapi/dochandler/updatehandler_test.go

The namespace for the document handler is now assumed to have no trailing delimiter (":"). The handler code will append the delimiter.
closes #74

feat: Remove trailing delimiter from doc namespace

---

pkg/api/batch/operation.go
pkg/dochandler/handler_test.go
pkg/processor/processor.go
pkg/processor/processor_test.go
pkg/restapi/dochandler/updatehandler.go

Fields operation number and previous operation hash are no longer used.
Closes #97

chore: Remove unused fields for update operation

---

pkg/api/batch/operation.go
pkg/processor/processor.go
pkg/processor/processor_test.go

Full operations (create, recover, delete) should be processed before update operations.
Apply update operations that where submitted after last full operation.
Closes #100

chore: Refactor the order of operation processing

---

pkg/api/batch/operation.go
pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/docutil/doc.go
pkg/docutil/hash.go
pkg/mocks/dochandler.go
pkg/processor/processor.go
pkg/processor/processor_test.go
pkg/restapi/diddochandler/restapi_test.go
pkg/restapi/diddochandler/updatehandler_test.go
pkg/restapi/dochandler/resolvehandler_test.go
pkg/restapi/dochandler/updatehandler.go
pkg/restapi/dochandler/updatehandler_test.go
pkg/restapi/model/header.go
pkg/restapi/model/request.go

Upon DID creation, the create operation payload must include:
-- The hash of a one-time password (OTP) for the next recovery operation.
-- The hash of a one-time password (OTP) for the next update operation.
The DID owner must reproduce and present the correct OTP in the subsequent operation for the operation to be considered valid. In addition, each subsequent operation must also include the hash of the new OTP(s) for the next operation. This scheme enables efficient dismissal of counterfeit operations without needing to evaluate signatures.
Closes #90

feat: One-time password for operations

---

pkg/dochandler/didvalidator/validator.go
pkg/dochandler/didvalidator/validator_test.go
pkg/dochandler/docvalidator/validator.go
pkg/dochandler/docvalidator/validator_test.go
pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/document/diddocument.go

Controller field in public key should be added upon document creation/resolution since it refers to document ID.
Also, it should not be provided in create request.
Closes #111

feat: Add "controller" field to public key

---

pkg/restapi/helper/request.go
pkg/restapi/helper/request_test.go
pkg/restapi/model/payload.go

Add REST helper functions for create and delete requests
-create
-delete (signed request)
Closes #125

feat: Add REST helper for creating requests

---

pkg/api/batch/operation.go
pkg/restapi/dochandler/payload_test.go
pkg/restapi/dochandler/resolvehandler_test.go
pkg/restapi/dochandler/updatehandler.go
pkg/restapi/dochandler/updatehandler_test.go

Currently for create request we require protected header and signature. Allow for latest create operation schema.
Closes #128

feat: Remove requirement for signature for create

---

ci/azure-pipelines.yml
pkg/processor/processor.go
pkg/processor/processor_test.go
pkg/restapi/dochandler/update.go
pkg/restapi/helper/request.go
pkg/restapi/model/request.go

-- Set json patch in operation data
-- Operations are filtered based on transaction number but should be filtered first by transactionTime and then by transactionNumber
-- Operations should be sorted by transactionTime/transactionNumber
Closes #137

fix: Update Issues

---

pkg/dochandler/docvalidator/validator.go
pkg/dochandler/docvalidator/validator_test.go

Change the field name from 'uniqueSuffix' to 'didUniqueSuffix'.
closes #139

fix: Document validator looks for incorrect unique suffix field

---

pkg/operation/create.go
pkg/operation/create_test.go
pkg/operation/revoke.go
pkg/operation/revoke_test.go
pkg/operation/update.go
pkg/operation/update_test.go
pkg/restapi/dochandler/resolvehandler_test.go
pkg/restapi/dochandler/updatehandler.go
pkg/restapi/dochandler/updatehandler_test.go

Operation parsing is currently used by REST API and will later be used when processing operations in anchor file.
Closes #

chore: Move parsing operation to separate package

---

pkg/observer/noopoperationfilter.go
pkg/observer/noopoperationfilter_test.go
pkg/observer/observer.go
pkg/observer/observer_test.go
pkg/processor/operationfilter.go
pkg/processor/operationfilter_test.go
pkg/processor/processor.go
pkg/processor/processor_test.go

The Observer ensures that only valid operations are persisted by applying all operations of a unique suffix (new and old) and discarding those that are not valid.
closes #124

feat: Filter out invalid operations at Observer

---

pkg/operation/create.go
pkg/operation/recover.go
pkg/restapi/dochandler/updatehandler.go
pkg/restapi/dochandler/updatehandler_test.go

Update handler is returning 'operation not supported' for recovery operation.
Add operation processing for 'recovery' operation to update handler.
Closes #147

fix: Enable recovery in update handler

---

pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/operation/create.go
pkg/operation/create_test.go
pkg/operation/recover.go
pkg/operation/recover_test.go
pkg/operation/revoke_test.go
pkg/operation/update.go
pkg/operation/update_test.go
pkg/processor/processor_test.go
pkg/restapi/diddochandler/updatehandler_test.go
pkg/restapi/dochandler/resolvehandler_test.go
pkg/restapi/helper/request.go
pkg/restapi/model/request.go

Replace all references of "operation data" to be "patch data" in code
Also signedOperationDataHash to signedData
Closes #156

chore: Rename operation data to patch data

---

pkg/api/batch/operation.go
pkg/dochandler/handler_test.go
pkg/operation/create.go
pkg/operation/create_test.go
pkg/operation/recover.go
pkg/operation/recover_test.go
pkg/operation/revoke.go
pkg/operation/revoke_test.go
pkg/operation/update.go
pkg/operation/update_test.go
pkg/processor/processor.go
pkg/processor/processor_test.go
pkg/restapi/diddochandler/updatehandler_test.go
pkg/restapi/dochandler/resolvehandler_test.go
pkg/restapi/dochandler/updatehandler_test.go
pkg/restapi/helper/request.go
pkg/restapi/helper/request_test.go
pkg/restapi/model/request.go

rename OTPHash to CommitmentHash
rename OTP to RevealValue
minor change for reveal value type in helper requests - makes it easier for client
Closes #153

chore: Rename OTP to commitment or reveal value

---

pkg/restapi/helper/request.go

- extract common patch data code in helper and increase coverage
- this code became common after the spec changed to use patches for 'create' and 'recover'
Closes #160

chore: consolidate common code for create patch data in helper

---

pkg/api/batch/operation.go
pkg/composer/composer.go
pkg/composer/composer_test.go
pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/mocks/dochandler.go
pkg/operation/create.go
pkg/operation/recover.go
pkg/operation/update.go
pkg/processor/processor.go
pkg/processor/processor_test.go
pkg/restapi/dochandler/resolvehandler_test.go

Add document composer for applying patches.
Modify operation model as follows:
-- remove document
-- add patch data and encoded patch data
Resolution with initial-value is also done via patches
Closes #167

feat: Add document composer for applying patches

---

pkg/observer/noopoperationfilter.go
pkg/observer/noopoperationfilter_test.go
pkg/observer/observer.go
pkg/observer/observer_test.go
pkg/processor/processor.go

Added an OperationStoreProvider which manages operation stores by namespace.
Also, created an Observer struct to contain Observer operations, including Start and Stop functions.
closes #169

feat: Allow for different operation store per namespace in Observer

---

pkg/composer/composer.go
pkg/dochandler/didvalidator/testdata/doc.json
pkg/dochandler/didvalidator/validator.go
pkg/dochandler/didvalidator/validator_test.go
pkg/document/diddocument.go
pkg/document/document.go
pkg/document/publickey.go
pkg/document/resolution.go
pkg/document/service.go
pkg/document/validator.go
pkg/document/validator_test.go

The object MUST include a usage property, and its value MUST be an array that includes one or more of the following strings:
ops: the key is allowed to generate DID operations for the DID.
general: the key is to be included in the publicKeys section of the resolved DID Document.
auth: the key is to be included in the authentication section of the resolved DID Document as follows:
- If the general usage value IS NOT present in the usage array, the key descriptor object will be included directly in the authentication section of the resolved DID Document.
- If the general usage value IS present in the usage array, the key descriptor object will be directly included in the publicKeys section of the resolved DID Document, and included by reference in the authentication section.
Closes #194 …

feat: Handle usage property

---

pkg/dochandler/didvalidator/validator.go
pkg/dochandler/didvalidator/validator_test.go
pkg/dochandler/docvalidator/validator.go
pkg/dochandler/docvalidator/validator_test.go
pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/document/diddocument.go
pkg/document/diddocument_test.go
pkg/document/document.go
pkg/document/document_test.go
pkg/document/resolution.go
pkg/document/testdata/doc.json
pkg/document/validator.go
pkg/mocks/dochandler.go
pkg/processor/processor.go
pkg/processor/processor_test.go
pkg/restapi/diddochandler/restapi_test.go
pkg/restapi/diddochandler/updatehandler_test.go
pkg/restapi/dochandler/resolvehandler.go
pkg/restapi/dochandler/resolvehandler_test.go
pkg/restapi/dochandler/updatehandler.go
pkg/restapi/dochandler/updatehandler_test.go

Resolution result contains:
-context
-document
-method metadata
Method metadata contains:
-operation public keys
-recovery key
-published flag
Closes #207

feat: Return resolution result instead of document

---

pkg/dochandler/didvalidator/testdata/doc.json
pkg/dochandler/didvalidator/validator.go
pkg/dochandler/didvalidator/validator_test.go
pkg/document/diddocument.go
pkg/document/diddocument_test.go
pkg/document/validator.go
pkg/document/validator_test.go

assertion: the key MUST be included in the assertionMethod section of the resolved DID Document, as follows:
If the general usage value IS NOT present in the usage array, the key descriptor object MUST be included directly in the assertionMethod section of the resolved DID Document.
If the general usage value IS present in the usage array, the key descriptor object MUST be directly included in the public keys section of the resolved DID Document, and MUST be included by relative DID URL reference in the assertionMethod section
Closes #215

feat: Support assertion key usage

---

pkg/dochandler/handler_test.go
pkg/docutil/doc_test.go
pkg/docutil/encoder.go
pkg/docutil/hash_test.go
pkg/operation/create_test.go
pkg/operation/deactivate_test.go
pkg/operation/recover_test.go
pkg/operation/update_test.go
pkg/processor/processor_test.go

Currently our DID contains invalid characters (such as '=' at the end) because we are using base64 encoding with padding. Use base64 URL encoding without padding for generating unique suffix and hashes.
Closes #218

fix: Use base64 encoding without padding

---

pkg/docutil/doc.go
pkg/docutil/doc_test.go

Currenlty we are doing decode before calculating multihash. Remove decode to match latest spec:
did = Base64URL(Multihash(DATA, 'sha2-256')));
There is no need for canonicalization before calculating did suffix because it is the client that sets suffix_data property of create request.
Closes #238

feat: Match latest unique suffix algorithm

---

pkg/api/protocol/protocol.go
pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/internal/request/method.go
pkg/internal/request/method_test.go
pkg/mocks/dochandler.go
pkg/mocks/protocol.go
pkg/restapi/dochandler/resolvehandler.go
pkg/restapi/dochandler/resolvehandler_test.go

Currently we are using create request in resolution with initial value.
Change existing solution to latest spec:
`did:METHOD:<did-suffix>?-METHOD-initial-state=<create-delta-object>.<create-suffix-data-object>`
Closes #240

refactor: Update resolution with initial state as per spec

---

pkg/restapi/diddochandler/restapi_test.go
pkg/restapi/diddochandler/updatehandler.go
pkg/restapi/diddochandler/updatehandler_test.go

chore: Renamed update REST endpoint to /operations

---

pkg/restapi/diddochandler/handler.go
pkg/restapi/diddochandler/resolvehandler.go
pkg/restapi/diddochandler/resolvehandler_test.go
pkg/restapi/diddochandler/restapi_test.go
pkg/restapi/diddochandler/updatehandler.go
pkg/restapi/diddochandler/updatehandler_test.go

Also refactored the handlers due to linter complaints about duplicate code.
closes #251

chore: Rename resolution endpoint to /identifiers

---

pkg/operation/recover_test.go
pkg/operation/update_test.go
pkg/restapi/dochandler/updatehandler_test.go
pkg/restapi/helper/request.go
pkg/restapi/helper/request_test.go
pkg/restapi/model/request.go
pkg/util/ecsigner/signer.go
pkg/util/edsigner/signer.go

Kid must not be provided for recovery and deactivate
Kid must be provided for update
Added signer validation in helper and accomodated helper signers for those scenarios
Also, included two more tests of operation validation (server side)
Closes #249

feat: Kid should not be provided for recovery and deactivate

---

pkg/dochandler/didvalidator/validator.go
pkg/dochandler/handler_test.go
pkg/internal/canonicalizer/canonicalizer.go
pkg/internal/canonicalizer/canonicalizer_test.go
pkg/internal/signutil/signature.go
pkg/internal/signutil/signature_test.go
pkg/operation/create_test.go
pkg/operation/deactivate_test.go
pkg/operation/recover_test.go
pkg/processor/processor.go
pkg/processor/processor_test.go
pkg/restapi/diddochandler/updatehandler_test.go
pkg/restapi/dochandler/resolvehandler_test.go
pkg/restapi/helper/create.go
pkg/restapi/helper/deactivate.go
pkg/restapi/helper/deactivate_test.go
pkg/restapi/helper/recover.go
pkg/restapi/helper/update.go
pkg/restapi/model/request.go

Included:
- add signed model for update, not just string (DELTA_HASH)
- remove option to update document using recovery key (doc has to have at least one ops key)
- check delta against signed delta hash for update and recovery
- validate info against signed data for deactivate
- organize tests for processor (move common code to internal: signing utility, canonicalization)
- update document context as per latest spec
Closes #250

feat: Add signed model for update

---

pkg/dochandler/didvalidator/validator.go
pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/internal/request/method.go
pkg/internal/request/method_test.go
pkg/mocks/dochandler.go
pkg/restapi/dochandler/resolvehandler.go
pkg/restapi/dochandler/resolvehandler_test.go

Fixed resolution and resolution with initial state to return bad request in case that user supplies invalid input
Operation processing has been fixed with issue #201 (operation validation on server side)
Closes #149

fix: Validation error of user request returns HTTP 500

---

pkg/composer/composer.go
pkg/composer/composer_test.go
pkg/dochandler/docvalidator/validator.go
pkg/dochandler/docvalidator/validator_test.go
pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/mocks/dochandler.go
pkg/operation/create_test.go
pkg/patch/patch.go
pkg/patch/patch_test.go
pkg/processor/processor.go
pkg/processor/processor_test.go
pkg/restapi/diddochandler/updatehandler_test.go
pkg/restapi/dochandler/resolvehandler_test.go
pkg/restapi/dochandler/updatehandler_test.go
pkg/restapi/helper/create.go
pkg/restapi/helper/recover.go

and replace it with add-public-keys, add-service-endpoints and ietf-json- patch
Process opaque document such that:
- public keys are handled with add public keys patch
- services are handled with add services patch
- everything else is handled by generic JSON patch
'replace' patch is no longer supported
Closes #265

refactor: Remove 'replace' patch

---

pkg/composer/composer_test.go
pkg/dochandler/handler_test.go
pkg/patch/patch.go
pkg/patch/patch_test.go
pkg/processor/processor_test.go

ietf-json-patch should not update public keys and services sections
Closes #253

chore: ietf-json-patch should not update keys and services

---

pkg/composer/composer_test.go
pkg/dochandler/handler_test.go
pkg/document/validator.go
pkg/document/validator_test.go
pkg/operation/create.go
pkg/operation/create_test.go
pkg/patch/patch.go
pkg/patch/patch_test.go

-- add validation for remove public keys and remove services (helper, operation processor)
-- add validation of all patches when parsing operation deltas ( this is server side validation before accepting operation request)
Also, fix regex for validate ID
Closes #175

chore: Add validation for remove public keys and remove services

---

pkg/document/validator.go
pkg/document/validator_test.go

Currently for service we are checking that we have only id, type and serviceEndpoint properties. Remove this restriction.
Closes #274

chore: Remove service validation for exact properties

---

pkg/api/batch/operation.go
pkg/dochandler/handler_test.go
pkg/operation/create.go
pkg/operation/deactivate.go
pkg/operation/recover.go
pkg/operation/update.go
pkg/processor/processor.go
pkg/processor/processor_test.go

Update and recovery commitment are already part of delta and signed model.
Hash is part of protocol.
Closes #282

chore: Remove duplicate/unused fields from operation model

---

pkg/api/batch/operation.go
pkg/batch/opqueue/memqueue_test.go
pkg/batch/writer.go
pkg/batch/writer_test.go
pkg/dochandler/handler.go
pkg/operation/operation.go
pkg/operation/operation_test.go
pkg/restapi/dochandler/updatehandler.go
pkg/restapi/dochandler/updatehandler_test.go

Batch writer should take as input operation buffer (sidetree request) instead of operation model and parse/validate operation buffer before creating chunk, map and anchor files.
Modify current batch writer code to accept and parse operation buffer (request).
Move common operation parsing code from update handler to operation package.
Closes #284

refactor: Batch Writer - parse/validate operation buffer

---

pkg/dochandler/didvalidator/testdata/doc.json
pkg/dochandler/didvalidator/validator.go
pkg/dochandler/didvalidator/validator_test.go
pkg/document/validator.go
pkg/document/validator_test.go

Allow specific optional service properties to be accepted in add service patch and return those properties in external document.
Closes #288

chore: Allow specific optional service properties

---

pkg/batch/cutter/cutter.go
pkg/batch/opqueue/memqueue.go
pkg/batch/opqueue/memqueue_test.go
pkg/batch/writer_test.go
pkg/mocks/operationqueue.gen.go

The operation queue interface is changed such that Remove function no longer returns the operations that were removed since this could impact performance in the case of a persistent queue implementation.
closes #117

refactor: Don't return removed operations from queue

---

pkg/api/cas/client.go
pkg/api/txn/sidetree.go
pkg/txnhandler/handler.go
pkg/txnhandler/handler_test.go
pkg/txnhandler/models/anchor.go
pkg/txnhandler/models/anchor_test.go
pkg/txnhandler/models/chunk.go
pkg/txnhandler/models/chunk_test.go
pkg/txnhandler/models/map.go
pkg/txnhandler/models/map_test.go

Transaction handler will:
-- prepare batch files(map, chunk, anchor) from batch operations for Sidetree transaction
-- parse operations from Sidetree transaction batch files(map, chunk, anchor) during observations time
Also, moved CAS interface and Sidetree txn definition to common api section
Closes #304

feat: transaction handler

---

pkg/api/protocol/protocol.go
pkg/batch/writer.go
pkg/mocks/protocol.go
pkg/observer/observer.go
pkg/observer/observer_test.go
pkg/txnhandler/handler.go
pkg/txnhandler/handler_test.go
pkg/txnhandler/models/anchor.go
pkg/txnhandler/provider.go
pkg/txnhandler/provider_test.go

Since transaction processor requires protocol client per namespace split transaction handler into two components:
-- operation handler (creates batch files from batch operations) - called by batch writer
-- operation processor (creates batch operations from batch files) - called by observer
Closes #308

refactor: Enable protocol client per namespace for observer

---

pkg/txnhandler/provider.go
pkg/txnhandler/provider_test.go

Wrong error is being logged thus causing nil pointer
Closes #310

fix: Nil pointer when logging parse anchor operations error

---

pkg/api/protocol/protocol.go
pkg/batch/writer.go
pkg/batch/writer_test.go
pkg/mocks/protocol.go
pkg/observer/observer.go
pkg/observer/observer_test.go
pkg/txnhandler/handler.go
pkg/txnhandler/handler_test.go
pkg/txnhandler/provider.go
pkg/txnhandler/provider_test.go

Add batch file compression/decompression to transaction handler:
-- compress batch files before storing them to CAS (batch writer)
-- decompress batch files upon retrieving them from CAS (observer)
-- check for maximum batch file size
Protocol:
-- add compression algorithm and maximum batch sizes
Closes: #318

feat: Add compression for batch files

---

pkg/batch/writer.go
pkg/batch/writer_test.go
pkg/observer/observer.go
pkg/observer/observer_test.go
pkg/txnhandler/provider.go
pkg/txnhandler/provider_test.go

Add following check when creating anchor, map, chunk files for Sidetree transaction:
- there can be only one operation per suffix in all batch files combined per transaction (log subsequent operations as warning and ignore them)
Add following check when processing Sidetree transaction operations during observation:
- if there is an operation with same suffix already in transaction do not process subsequent operations with same suffix. This should never happen because of check during batch file creation. Ignored operations should be logged as warning but not be stored for future processing.
Add following check for Sidetree transaction during observation:
- number of operations in anchor string has to match number of operations in anchor + map file
Closes #320
Signed-off-by: Sandra Vrtikapa …

chore: Add common validations for batch files

---

pkg/batch/writer_test.go

Batch cutting time has increased due to more processing (compression, validation etc) so we have to increase sleep time in TestStartWithExistingItems. Test is failing more often in CI recently (it never fails locally).
Closes #322

fix: Increase unit-test sleep time

---

pkg/commitment/hash.go
pkg/commitment/hash_test.go
pkg/internal/signutil/signature.go
pkg/internal/signutil/signature_test.go
pkg/operation/deactivate.go
pkg/operation/deactivate_test.go
pkg/operation/operation.go
pkg/operation/operation_test.go
pkg/operation/recover.go
pkg/operation/recover_test.go
pkg/operation/update.go
pkg/operation/update_test.go
pkg/processor/processor.go
pkg/processor/processor_test.go

In order to make update, recover, deactivate tests from reference implementation work, following fixes need to be applied:
- signature payload should not be encoded
Closes #331

chore: Signature payload should not be encoded

---

pkg/dochandler/handler_test.go
pkg/docutil/hash.go
pkg/docutil/hash_test.go
pkg/operation/create.go
pkg/operation/create_test.go
pkg/operation/recover_test.go
pkg/operation/update_test.go
pkg/processor/processor.go
pkg/processor/processor_test.go
pkg/restapi/diddochandler/updatehandler_test.go
pkg/txnhandler/models/anchor.go
pkg/txnhandler/models/map.go

Add verification that suffix data delta hash matches provided delta:
- during operation validation for create
- when applying create operation during resolution
Closes #338

chore: verify suffix data delta hash against delta (create)

---

pkg/processor/operationfilter.go
pkg/processor/processor.go
pkg/processor/processor_test.go

During resolution we should apply create operations first, specifically first valid create operation.
https://identity.foundation/sidetree/spec/#create-operation-pool
Closes #341

chore: Apply create operations first (during resolution)

---

pkg/api/protocol/protocol.go
pkg/mocks/protocol.go
pkg/operation/create.go
pkg/operation/create_test.go
pkg/operation/deactivate.go
pkg/operation/operation_test.go
pkg/operation/recover.go
pkg/operation/recover_test.go
pkg/operation/update.go
pkg/operation/update_test.go
pkg/processor/processor.go
pkg/processor/processor_test.go
pkg/txnhandler/provider.go
pkg/txnhandler/provider_test.go

Add to protocol interface get function for retrieving protocol parameters by transaction number (block number). So far we were only retrieving latest protocol.
Also, re-used common code for parsing signed data.
Closes #348

feat: Get protocol parameters by transaction number

---

pkg/txnhandler/models/anchor.go
pkg/txnhandler/models/chunk.go
pkg/txnhandler/models/map.go
pkg/txnhandler/provider.go
pkg/txnhandler/provider_test.go

Add check that matches number of create, update and recover operations with number of deltas in chunk file.
Closes #296

chore: complete chunk file validation rules

---

pkg/restapi/helper/deactivate.go
pkg/restapi/helper/deactivate_test.go
pkg/restapi/helper/recover.go
pkg/restapi/helper/recover_test.go
pkg/restapi/helper/update.go
pkg/restapi/helper/update_test.go
pkg/util/ecsigner/signer.go
pkg/util/edsigner/signer.go

Implement latest protected header validation rules:
- kid MUST be present in the protected header
- alg MUST be present in the protected header, its value MUST NOT be none
- no additional members may be present in the protected header
Closes #325

chore: protected header validation rules

---

pkg/api/batch/operation.go
pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/mocks/dochandler.go
pkg/operation/create.go
pkg/operation/recover.go
pkg/operation/update.go
pkg/processor/processor.go
pkg/processor/processor_test.go
pkg/restapi/dochandler/resolvehandler_test.go
pkg/txnhandler/models/anchor.go
pkg/txnhandler/models/anchor_test.go
pkg/txnhandler/models/chunk.go
pkg/txnhandler/provider.go
pkg/txnhandler/provider_test.go

Included:
- use underscores for internal JSON model
- rename anchored operation model fields to match batch files fields
- remove JSON tags from operation model (used for parsing and validating)
- rename operation model fields to match anchored operation model fields
- removed txn fields from operation model
Closes #221

chore: use underscores for internal JSON model

---

pkg/api/protocol/protocol.go
pkg/dochandler/handler_test.go
pkg/operation/create.go
pkg/operation/create_test.go
pkg/operation/recover.go
pkg/operation/update.go
pkg/operation/update_test.go
pkg/processor/processor.go
pkg/txnhandler/provider.go

Add ability to enable 'replace' patch (it will be used for interop tests)
Closes #339

chore: add ability to enable 'replace' patch

---

pkg/composer/composer.go
pkg/composer/composer_test.go

When patches are applied preserve the order of public keys and services.
Closes #361

chore: preserve the order of pub keys and services

---

pkg/api/protocol/protocol.go
pkg/mocks/protocol.go
pkg/operation/deactivate.go
pkg/operation/deactivate_test.go
pkg/operation/operation_test.go
pkg/operation/recover.go
pkg/operation/recover_test.go
pkg/operation/update.go
pkg/operation/update_test.go
pkg/processor/processor.go
pkg/processor/processor_test.go

Add validation of supported algorithms for signed data for update, deactivate and recover operations at request time. Supported algorithms are: EdDSA, ES256, ES384, ES512, ES256K.
Add new parameter to protocol parameters called signature algorithms that will allow configuring supported algorithms.
Closes #198

chore: add configuration and validation of supported algorithms for signing

---

pkg/api/protocol/protocol.go
pkg/mocks/protocol.go
pkg/operation/deactivate.go
pkg/operation/deactivate_test.go
pkg/operation/operation_test.go
pkg/operation/recover.go
pkg/operation/recover_test.go
pkg/operation/update.go
pkg/operation/update_test.go
pkg/restapi/dochandler/resolvehandler_test.go
pkg/txnhandler/handler_test.go

Add validation of supported key algorithms for signed operations at request time. Supported key algorithms for 'crv' are: Ed25519, secp256k1, P-256, P-384, P-512.
Add new parameter to protocol parameters called key algorithms that will allow configuring supported key algorithms.
Closes #364

chore: Add validation of supported key algorithms for signed operations

---

go.mod
go.sum
pkg/api/protocol/protocol.go
pkg/batch/cutter/cutter.go
pkg/batch/cutter/cutter_test.go
pkg/batch/writer_test.go
pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/mocks/protocol.go

Change MaxDeltaSizeInBytes to MaxOperationSize and adjust validations for operations and resolution with initial value.
Rename:
MaxOperationsPerBatch to MaxOperationCount
StartingBlockChainTime to GenesisTime
Closes #368

chore: Rename protocol parameters as per spec

---

docs/source/overview.rst
pkg/composer/composer_test.go
pkg/dochandler/didvalidator/testdata/doc.json
pkg/dochandler/didvalidator/validator_test.go
pkg/dochandler/docvalidator/validator_test.go
pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/document/diddocument_test.go
pkg/document/testdata/doc.json
pkg/document/validator.go
pkg/document/validator_test.go
pkg/internal/request/method.go
pkg/operation/create_test.go
pkg/patch/patch_test.go
pkg/processor/processor_test.go
pkg/restapi/diddochandler/doc.go
pkg/restapi/diddochandler/updatehandler_test.go
pkg/restapi/dochandler/updatehandler_test.go

Ops purpose is no longer valid; remove all references to "ops" purpose
Also, minor changes to comments that got out of sync with spec.
Closes #375

chore: remove references to 'ops' purpose

---

pkg/composer/composer.go
pkg/composer/composer_test.go
pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/mocks/dochandler.go
pkg/processor/processor.go

Sidetree-core logic:  if applying patch fails the whole operation fails
Spec and reference implementation: If applying patch fails we should continue to the next patch in patches array.
Closes #377

chore: If applying patch fails we should continue to the next patch

---

pkg/hashing/registry.go
pkg/hashing/registry_test.go
pkg/hashing/sha256/algorithm.go
pkg/hashing/sha256/algorithm_test.go

Add registry for hashing algorithms; include SHA256 implementation.
Closes #395

chore: add registry for hashing algorithms

---

docs/source/overview.rst
pkg/dochandler/handler.go
pkg/internal/request/method.go
pkg/internal/request/method_test.go
pkg/restapi/diddochandler/doc.go

Currently we are supporting the following long form DID format:
did:METHOD:did-suffix?initial-state=create-suffix-data-object.create-delta-object
This PR implements second long form DID format:
did:METHOD:did-suffix:create-suffix-data-object.create-delta-object
Closes #398

feat: Additional long form DID format

---

pkg/internal/request/method.go
pkg/internal/request/method_test.go

This was introduced with additional long form DID format because it treats is as long form resolution. Do not check for . in namespace.
Closes #402

fix: resolution fails if namespace has . in it

---

pkg/document/jwk.go
pkg/document/jwk_test.go
pkg/document/validator.go
pkg/document/validator_test.go
pkg/patch/patch_test.go
pkg/restapi/dochandler/updatehandler_test.go
pkg/restapi/helper/create.go
pkg/restapi/helper/create_test.go
pkg/restapi/helper/recover.go
pkg/restapi/helper/recover_test.go
pkg/restapi/helper/update.go
pkg/restapi/helper/update_test.go
pkg/versions/0_1/txnprovider/handler_test.go

Add ability to specify multiple patches for create, recover, update in restapi helper.
Closes #406

chore: Add multiple patches for create/recover/update in helper

---

pkg/versions/0_1/doccomposer/composer.go
pkg/versions/0_1/doccomposer/composer_test.go

Apply patches should not modify original document. Instead, make a copy of the original document and apply patches on that copy.
Closes #410

fix: Apply patches should not modify original document in case of error

---

pkg/api/batch/operation.go
pkg/versions/0_1/txnprocessor/txnprocessor.go
pkg/versions/0_1/txnprocessor/txnprocessor_test.go

Leftover from previous versions, not used any more.
Closes #419

chore: remove unused operation index from anchor model

---

pkg/api/protocol/protocol.go
pkg/mocks/protocol.go
pkg/mocks/protocolversion.gen.go

A Version() function was added to the protocol.Version interface.
closes #421

feat: Added version string to protocol.Version

---

pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/mocks/dochandler.go
pkg/restapi/dochandler/resolvehandler.go
pkg/restapi/dochandler/resolvehandler_test.go

If alias namespace was used to resolve did, add canonical ID if document has been published.
Closes #427

feat: Add canonical id to document

---

pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/document/resolution.go

Currently we have canonical ID in DID document. Since there is no movement in adding canonical ID to did-core @troyronda requested we are going to move this field to method metadata.
Closes #435

chore: Move canonical id from doc to resolution result (method metadata)

---

pkg/api/protocol/protocol.go
pkg/dochandler/handler.go
pkg/mocks/dochandler.go
pkg/mocks/operationparser.gen.go
pkg/restapi/dochandler/resolvehandler_test.go
pkg/versions/0_1/operationparser/method.go
pkg/versions/0_1/operationparser/method_test.go

Parsing of initial state during long form resolution should be versioned. Move this functionality to operation parser.
Closes #441

chore: Version parsing of initial state

---

pkg/batch/writer_test.go
pkg/processor/processor_test.go
pkg/restapi/dochandler/updatehandler_test.go
pkg/versions/0_1/client/create.go
pkg/versions/0_1/client/create_test.go
pkg/versions/0_1/client/deactivate.go
pkg/versions/0_1/client/deactivate_test.go
pkg/versions/0_1/client/recover.go
pkg/versions/0_1/client/recover_test.go
pkg/versions/0_1/client/update.go
pkg/versions/0_1/client/update_test.go
pkg/versions/0_1/operationapplier/operationapplier_test.go
pkg/versions/0_1/operationparser/commitment_test.go
pkg/versions/0_1/txnprovider/handler_test.go

Currently package restapi/helper  is used to assemble Sidetree request based on provided information. 
Included:
- rename helper to client
- move helper/client to versioned folder
Closes #443

chore: rename and version REST helper

---

pkg/dochandler/transformer/doctransformer/transformer.go
pkg/dochandler/transformer/doctransformer/transformer_test.go

There is no need for generic document to have public keys in the document. The requirement for update key to be part of the document has been removed couple of months ago. This is leftover code - not used any more.
Closes #450

chore: Remove public keys processing from generic document transformer

---

pkg/patch/patch.go
pkg/patch/patch_test.go
pkg/versions/0_1/operationparser/patchvalidator/addservices_test.go
pkg/versions/0_1/operationparser/patchvalidator/removekeys_test.go
pkg/versions/0_1/operationparser/patchvalidator/removeservices_test.go

Spec has been changed for remove-public-keys patch to use ids tag instead of publicKeys.
Closes #451

chore: Remove-public-keys patch should use ids tag instead of publicKeys

---

pkg/api/protocol/protocol.go
pkg/mocks/protocol.go
pkg/processor/processor.go
pkg/processor/processor_test.go
pkg/versions/0_1/operationapplier/operationapplier_test.go
pkg/versions/0_1/operationparser/commitment_test.go
pkg/versions/0_1/operationparser/create.go
pkg/versions/0_1/operationparser/create_test.go
pkg/versions/0_1/operationparser/deactivate_test.go
pkg/versions/0_1/operationparser/operation_test.go
pkg/versions/0_1/operationparser/recover.go
pkg/versions/0_1/operationparser/recover_test.go
pkg/versions/0_1/operationparser/update.go
pkg/versions/0_1/operationparser/update_test.go
pkg/versions/0_1/txnprovider/provider.go
pkg/versions/0_1/txnprovider/provider_test.go

Rename:
- rename tag multiHashAlgorithm to multihashAlgorithm
- rename corresponding struct field HashAlgorithmInMultiHashCode
Closes #449

chore: Rename HashAlgorithmInMultiHashCode to MultihashAlgorithm

---

pkg/dochandler/transformer/didtransformer/transformer.go
pkg/dochandler/transformer/didtransformer/transformer_test.go
pkg/document/diddocument.go
pkg/document/resolution.go

Reference application is producing DIDs with @base context. Add this functionality as configuration property.
Closes #457

chore: Support @base as configuration option

---

pkg/batch/writer_test.go
pkg/versions/0_1/txnprovider/handler.go
pkg/versions/0_1/txnprovider/handler_test.go
pkg/versions/0_1/txnprovider/models/anchor.go
pkg/versions/0_1/txnprovider/models/anchor_test.go
pkg/versions/0_1/txnprovider/models/coreproof.go
pkg/versions/0_1/txnprovider/models/coreproof_test.go
pkg/versions/0_1/txnprovider/models/map.go
pkg/versions/0_1/txnprovider/models/provisionalproof.go
pkg/versions/0_1/txnprovider/models/provisionalproof_test.go
pkg/versions/0_1/txnprovider/models/signed.go

Included:
- core and provisional proof file models
- writing of proof files to CAS
Closes #459

feat: Add core, provisional proof files

---

pkg/dochandler/handler_test.go
pkg/dochandler/transformer/didtransformer/testdata/doc.json
pkg/dochandler/transformer/didtransformer/transformer.go
pkg/dochandler/transformer/didtransformer/transformer_test.go
pkg/document/diddocument.go
pkg/document/diddocument_test.go
pkg/document/document_test.go
pkg/document/publickey.go
pkg/document/testdata/pk-doc.json
pkg/document/testdata/vm-doc.json
pkg/patch/patch_test.go
pkg/processor/processor_test.go
pkg/restapi/diddochandler/updatehandler_test.go
pkg/restapi/dochandler/updatehandler_test.go
pkg/versions/0_1/client/create_test.go
pkg/versions/0_1/doccomposer/composer_test.go
pkg/versions/0_1/docvalidator/didvalidator/testdata/doc.json
pkg/versions/0_1/docvalidator/didvalidator/validator_test.go
pkg/versions/0_1/operationapplier/operationapplier_test.go
pkg/versions/0_1/operationparser/create_test.go
pkg/versions/0_1/operationparser/patchvalidator/addkeys_test.go
pkg/versions/0_1/operationparser/patchvalidator/document.go
pkg/versions/0_1/operationparser/patchvalidator/document_test.go
pkg/versions/0_1/operationparser/patchvalidator/replace_test.go
pkg/versions/0_1/operationparser/patchvalidator/testdata/doc.json

During transformation:
- use 'verificationMethod' tag instead of 'publicKey' tag for external document
- verificationMethod is implied for any key - it should not be passed in as "purpose"
- keys can no longer be embedded in purpose sections such as "authentication" etc.
- keys are always placed in "verficationMethod"
- keys are referenced in purpose sections if "purpose" has been specified
- keys in purposes sections are now referenced by "full" id and not as "fragment"
Closes #462

feat: Handle purposes as per latest spec

---

pkg/api/protocol/protocol.go
pkg/batch/writer_test.go
pkg/mocks/protocol.go
pkg/processor/processor_test.go
pkg/versions/0_1/operationapplier/operationapplier_test.go
pkg/versions/0_1/txnprovider/handler.go
pkg/versions/0_1/txnprovider/handler_test.go
pkg/versions/0_1/txnprovider/models/anchor.go
pkg/versions/0_1/txnprovider/models/anchor_test.go
pkg/versions/0_1/txnprovider/models/chunk.go
pkg/versions/0_1/txnprovider/models/common.go
pkg/versions/0_1/txnprovider/models/map.go
pkg/versions/0_1/txnprovider/models/map_test.go
pkg/versions/0_1/txnprovider/provider.go
pkg/versions/0_1/txnprovider/provider_test.go

Included:
- organize operations by type for batch file creation and processing
- collect batch files into one struct for assembling operations (too many files as params)
- rename Anchor and Map Files to Core Index and Provisional Index Files
- move Provisional Proof URI to Provisional Index File
Closes #468

chore: SIP-1: Core and Provisional Index Files

---

pkg/versions/0_1/txnprovider/models/common.go
pkg/versions/0_1/txnprovider/provider.go
pkg/versions/0_1/txnprovider/provider_test.go

When assembling anchored operations retrieve signed data from proof files.
Closes #470

feat: use signed data from proof files for anchored operations

---

pkg/api/protocol/protocol.go
pkg/versions/0_1/operationparser/recover.go
pkg/versions/0_1/operationparser/recover_test.go

Spec has been updated to "kid MAY be present in the protected headers". Remove commented out code.
Also, included fix for JSON tag: 'maxCoreIndexFileSize'
Closes #365

chore: remove references to kid MUST be present in protected headers

---

pkg/versions/0_1/txnprovider/models/common.go
pkg/versions/0_1/txnprovider/models/coreindex.go
pkg/versions/0_1/txnprovider/models/provisionalindex.go
pkg/versions/0_1/txnprovider/provider.go
pkg/versions/0_1/txnprovider/provider_test.go

Rename SignedOperation to OperationReference (to align naming with reference app)
Closes #489

chore: Rename SignedOperation to OperationReference

---

pkg/processor/processor.go
pkg/versions/0_1/txnprovider/provider.go
pkg/versions/0_1/txnprovider/provider_test.go

Transaction Processor:
- return an error if there are duplicate suffixes in core index file
- clarify log for operation commitment equals next operation commitment
Closes #493

chore: return an error if there are duplicate suffixes in core index

---

pkg/versions/0_1/txnprovider/models/coreindex.go
pkg/versions/0_1/txnprovider/provider_test.go

Rename CreateOperation to CreateReference (to align naming with reference app)
Closes #498

chore: Rename CreateOperation to CreateReference (core index)

---

pkg/batch/writer_test.go
pkg/restapi/dochandler/resolvehandler_test.go
pkg/restapi/dochandler/updatehandler_test.go
pkg/versions/0_1/client/create.go
pkg/versions/0_1/client/create_test.go
pkg/versions/0_1/client/recover.go
pkg/versions/0_1/client/recover_test.go
pkg/versions/0_1/client/update.go
pkg/versions/0_1/client/update_test.go
pkg/versions/0_1/operationapplier/operationapplier.go
pkg/versions/0_1/operationapplier/operationapplier_test.go
pkg/versions/0_1/operationparser/commitment_test.go
pkg/versions/0_1/operationparser/create.go
pkg/versions/0_1/operationparser/create_test.go
pkg/versions/0_1/operationparser/operation.go
pkg/versions/0_1/operationparser/recover.go
pkg/versions/0_1/operationparser/recover_test.go
pkg/versions/0_1/operationparser/update.go
pkg/versions/0_1/operationparser/update_test.go
pkg/versions/0_1/txnprovider/handler_test.go
pkg/versions/0_1/txnprovider/models/coreindex.go

Add checks for re-using commitments to client and operation parser
Closes #502

chore: Add checks for re-using commitments (client, operation parser)

---

pkg/processor/processor_test.go
pkg/restapi/dochandler/updatehandler_test.go
pkg/util/ecsigner/signer.go
pkg/util/ecsigner/signer_test.go
pkg/util/edsigner/signer.go
pkg/util/edsigner/signer_test.go
pkg/versions/0_1/client/deactivate.go
pkg/versions/0_1/client/deactivate_test.go
pkg/versions/0_1/client/update_test.go
pkg/versions/0_1/operationparser/commitment_test.go
pkg/versions/0_1/txnprovider/handler_test.go

Remove "kid must be present in the protected headers" rule in the client
Also, if empty don't add kid, alg to the headers of utility signers.
Closes #503

chore: Remove "kid must be present in the protected headers" for client

---

go.mod
pkg/document/service.go
pkg/versions/0_1/doctransformer/didtransformer/testdata/doc.json
pkg/versions/0_1/doctransformer/didtransformer/transformer_test.go
pkg/versions/0_1/operationparser/patchvalidator/document.go
pkg/versions/0_1/operationparser/patchvalidator/document_test.go

Add support for service endpoint as either URI string or  "JSON object with properties that describe the Service Endpoint further." Also, remove check for service endpoint URI length (no longer in spec)
Closes #508

chore: Add support for service endpoint object

---

pkg/versions/0_1/operationapplier/operationapplier.go
pkg/versions/0_1/operationapplier/operationapplier_test.go

Even if applying patches for update operation fails we should advance update commitment. This is consistent with recover operation.
This was agreed on today's  Sidetree weekly.
Closes #510

chore: Advance update commitment if possible for update operation

---

pkg/dochandler/handler_test.go
pkg/document/resolution.go
pkg/mocks/transformer.go
pkg/versions/0_1/doctransformer/didtransformer/transformer.go
pkg/versions/0_1/doctransformer/didtransformer/transformer_test.go
pkg/versions/0_1/doctransformer/doctransformer/transformer.go
pkg/versions/0_1/doctransformer/doctransformer/transformer_test.go

Created new did document metadata section in the resolution result and set canonicalId there
Closes #514

chore: move canonicalId to did document metadata

---

pkg/api/protocol/protocol.go
pkg/mocks/cas.go
pkg/mocks/protocol.go
pkg/processor/processor_test.go
pkg/versions/0_1/operationapplier/operationapplier_test.go
pkg/versions/0_1/txnprovider/provider.go
pkg/versions/0_1/txnprovider/provider_test.go

Included: 
- new protocol parameter maxCasUriLength
- added validation of CAS file URIs in batch files
Closes #477

chore: add validation of CAS file URI in batch files

---

pkg/versions/0_1/operationparser/patchvalidator/document.go
pkg/versions/0_1/operationparser/patchvalidator/document_test.go

Add validation for duplicate service id to "add-services" patch
Closes #518

chore: add-services patch should not allow duplicate service ids

---

pkg/api/protocol/protocol.go
pkg/mocks/protocol.go
pkg/processor/processor_test.go
pkg/versions/0_1/operationapplier/operationapplier_test.go
pkg/versions/0_1/operationparser/create.go
pkg/versions/0_1/operationparser/create_test.go
pkg/versions/0_1/operationparser/deactivate.go
pkg/versions/0_1/operationparser/deactivate_test.go
pkg/versions/0_1/operationparser/operation_test.go
pkg/versions/0_1/operationparser/recover.go
pkg/versions/0_1/operationparser/recover_test.go
pkg/versions/0_1/operationparser/update.go
pkg/versions/0_1/operationparser/update_test.go
pkg/versions/0_1/txnprovider/provider.go
pkg/versions/0_1/txnprovider/provider_test.go

Add MAX_OPERATION_HASH_LENGTH parameter to protocol and validate the following values against it:
- did suffix and reveal value in core index file (reference operation is generated by batch writer/values to be checked in observer)
- deltaHash, recoveryCommitment (suffix data) - input
- updateCommitment(delta) - input
- deltaHash, recoveryCommitment - JWS (recovery) - input
Closes #517

feat: Add max operation hash length protocol parameter

---

pkg/api/protocol/protocol.go
pkg/hashing/hash.go
pkg/hashing/hash_test.go
pkg/mocks/protocol.go
pkg/processor/processor_test.go
pkg/versions/0_1/client/create.go
pkg/versions/0_1/model/util.go
pkg/versions/0_1/model/util_test.go
pkg/versions/0_1/operationapplier/operationapplier_test.go
pkg/versions/0_1/operationparser/commitment_test.go
pkg/versions/0_1/operationparser/create.go
pkg/versions/0_1/operationparser/create_test.go
pkg/versions/0_1/operationparser/deactivate_test.go
pkg/versions/0_1/operationparser/operation_test.go
pkg/versions/0_1/operationparser/recover.go
pkg/versions/0_1/operationparser/recover_test.go
pkg/versions/0_1/operationparser/update.go
pkg/versions/0_1/operationparser/update_test.go
pkg/versions/0_1/txnprovider/provider.go
pkg/versions/0_1/txnprovider/provider_test.go

Add support for an array of multihash algorithms in protocol.
As per Sidetree working group the first version of the protocol should support one algorithm only and unique suffix should be calculated based on that version. Created follow-up issue for protocol version 2 (#528)
Closes #522

feat: support multiple multihash algorithms in protocol

---

pkg/dochandler/handler.go
pkg/dochandler/handler_test.go

Reject create operation at API layer when applying patches fails (e.g. resulting document is empty)
Currently, at the API layer, when user submits a create operation we accept delta that may result in an error during applying patches. The DID will be created with the commit reveal value but it won't be able to apply delta and the resulting document will be empty. We have an opportunity to gate this "half failed" operation at the API layer. This requires the API to behave differently from observer, but provides a better user experience. So basically we would fail for every create that results in an empty document. 
Closes #527

chore: Reject create operation at API layer when applying patches results in an empty document

---

pkg/api/protocol/protocol.go
pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/document/resolution.go
pkg/mocks/dochandler.go
pkg/mocks/transformer.go
pkg/processor/processor.go
pkg/processor/processor_test.go
pkg/restapi/dochandler/resolvehandler.go
pkg/versions/0_1/doctransformer/didtransformer/transformer.go
pkg/versions/0_1/doctransformer/didtransformer/transformer_test.go
pkg/versions/0_1/doctransformer/doctransformer/transformer.go
pkg/versions/0_1/doctransformer/metadata.go
pkg/versions/0_1/doctransformer/metadata_test.go
pkg/versions/0_1/operationapplier/operationapplier.go

Included:
- align resolution object with did core spec (method metadata moved to document metadata)
- add 'deactivated' flag to document metadata
- add 'equivalentId' for long form resolution
- return 'canonicalId' for all published documents
Created #535 for follow-up regarding questions posted to Sidetree slack regarding deactivate and controller.
Closes #534

feat: Align with core did spec

---

pkg/api/operation/models.go
pkg/api/protocol/protocol.go
pkg/batch/writer.go
pkg/mocks/blockchain.go
pkg/mocks/operationhandler.gen.go
pkg/versions/0_1/txnprovider/handler.go
pkg/versions/0_1/txnprovider/handler_test.go
pkg/versions/0_1/txnprovider/provider_test.go

When creating Sidetree transaction  it can be beneficial to know minimum information about did operations that are referenced in Sidetree batch files:
- return operation references upon creating batch files
- pass operation references when writing transaction 
Closes #539

Return operation references upon creating batch files 

---

pkg/restapi/dochandler/resolvehandler.go
pkg/restapi/dochandler/resolvehandler_test.go
pkg/versions/0_1/doctransformer/didtransformer/transformer.go
pkg/versions/0_1/doctransformer/metadata.go

Included:
- deactivate returns HTTP 200 instead of 410
Closes #535

chore: align with did core follow-up

---

pkg/api/operation/models.go
pkg/api/protocol/protocol.go
pkg/batch/writer.go
pkg/batch/writer_test.go
pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/mocks/blockchain.go
pkg/mocks/protocol.go
pkg/processor/processor_test.go
pkg/versions/0_1/txnprocessor/txnprocessor.go

Rename BlockchainClient to AnchorWriter and modify references to blockchain accordingly.
Closea #548

chore: rename blockchain client to anchor writer

---

pkg/versions/0_1/client/create.go
pkg/versions/0_1/client/create_test.go
pkg/versions/0_1/client/recover.go
pkg/versions/0_1/client/recover_test.go
pkg/versions/0_1/model/request.go
pkg/versions/0_1/operationparser/create.go
pkg/versions/0_1/operationparser/create_test.go
pkg/versions/0_1/operationparser/operation.go
pkg/versions/0_1/operationparser/operation_test.go
pkg/versions/0_1/operationparser/recover.go
pkg/versions/0_1/operationparser/recover_test.go
pkg/versions/0_1/txnprovider/handler_test.go

Add optional anchor origin in:
- suffix data for create operation
- signed model for recover operation
Add anchor origin object validator to parser and validate anchor origin against it. Default object validator accepts all objects.
Closes #546

feat: Add support for anchor origin

---

pkg/versions/0_1/client/deactivate.go
pkg/versions/0_1/client/recover.go
pkg/versions/0_1/client/update.go
pkg/versions/0_1/model/request.go
pkg/versions/0_1/operationparser/create.go
pkg/versions/0_1/operationparser/create_test.go
pkg/versions/0_1/operationparser/deactivate.go
pkg/versions/0_1/operationparser/operation.go
pkg/versions/0_1/operationparser/operation_test.go
pkg/versions/0_1/operationparser/recover.go
pkg/versions/0_1/operationparser/recover_test.go
pkg/versions/0_1/operationparser/update.go
pkg/versions/0_1/txnprovider/handler.go
pkg/versions/0_1/txnprovider/handler_test.go

Included: 
- anchor origin should only be checked at REST/Batch Writer points 
- add anchor from and anchor until to client interface and Sidetree model
- add validation of anchor from and anchor at REST and Batch Writer points
- ignore expired operations when creating Sidetree batches
TODO (in different PR): 
- add validation of anchor from and anchor until to operation applier (will be checked against anchoring time)
- add protocol parameter MAX_OPERATION_TIME_DELTA  to calculate until time if from time is provided and until time is not provided
Closes #547

chore: Implement anchor from and until

---

pkg/api/protocol/protocol.go
pkg/mocks/protocol.go
pkg/versions/0_1/operationapplier/operationapplier.go
pkg/versions/0_1/operationapplier/operationapplier_test.go
pkg/versions/0_1/operationparser/deactivate.go
pkg/versions/0_1/operationparser/deactivate_test.go
pkg/versions/0_1/operationparser/recover.go
pkg/versions/0_1/operationparser/update.go

If anchor from time is provided and anchor until time is not provided calculate until time by adding max operation time delta to from time.
Closes #555

feat: Add protocol parameter MAX_OPERATION_TIME_DELTA

---

pkg/api/protocol/protocol.go
pkg/mocks/txnprocessor.gen.go
pkg/versions/1_0/txnprocessor/txnprocessor.go

In order to enable processing batch files per suffix we have to modify transaction processor interface to accept optional did suffixes.
Closes #574

chore: Enable processing batch files per suffix

---

pkg/dochandler/handler.go

Fix the order for namespace checking: aliases should be checked first since true namespace can be a subset of alias.
Closes #578

fix: Fix the order for namespace checking

---

pkg/dochandler/handler.go
pkg/dochandler/handler_test.go

If domain is specified for document handler create an equivalent ID with "interim:domain" hint for the result of create operation (unpublished DID document)
Closes #582

chore: Add support for "interim" hint in unpublished DIDs

---

pkg/document/document.go
pkg/document/document_test.go
pkg/document/publickey_test.go
pkg/versions/1_0/doctransformer/didtransformer/transformer.go
pkg/versions/1_0/doctransformer/didtransformer/transformer_test.go

DID WG is deleted crypto suite’s contexts from the core did context.
Add relevant context to did document (based on the public key types that are actually in the did document).
Closes #570

Add relevant key context to did document

---

go.sum
pkg/batch/writer.go

This commit ensures that the batch writer timer is always running, even if no operations were added. Previously, the batch writer timer was only started if an operation had been added locally. In the case where the operation queue is distributed (e.g. message broker) then an operation may have been added to Server1, published to a distributed queue and delivered to Server2, but the timer was not started on Server2 and so the message was not processed (until another operation is added to Server2).
closes #590

fix: Always start batch writer timer

---

pkg/canonicalizer/canonicalizer.go
pkg/canonicalizer/canonicalizer_test.go

Currently MarshalCanonical will return an error if bytes are passed in since json.Marshal fails for bytes. Do not marshal if bytes are passed in.
Closes #593

chore: Handle bytes input for MarshalCanonical

---

pkg/batch/writer.go

Unnecessary info logs were being generated every time a batch writer timeout occurred so the log level was set to debug.

chore: Change logging level to Debug for batch writer

---

pkg/api/operation/models.go
pkg/batch/cutter/cutter.go
pkg/batch/cutter/cutter_test.go
pkg/batch/opqueue/memqueue.go
pkg/batch/opqueue/memqueue_test.go
pkg/batch/writer.go
pkg/batch/writer_test.go
pkg/mocks/operationqueue.gen.go

Added explicit 'Ack' and 'Nack' capability when operations are removed from the queue. When Remove is invoked, the return values are 'Ack' and 'Nack' functions. The 'Ack' function commits the remove and the 'Nack' function ensures that the operations remain in the queue so that they may be retried.
closes #596

feat: Operation queue Ack/Nack

---

pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/processor/processor.go
pkg/processor/processor_test.go
pkg/versions/1_0/txnprocessor/txnprocessor.go
pkg/versions/1_0/txnprocessor/txnprocessor_test.go

Add unpublished operation store option to the following components:
1. resolver (add unpublished operation to the unpublished operation store during ingestion)
2. operation processor (add operation from unpublished store to the operations from published store and assemble document)
3. txn processor (will delete all unpublished operations once they are published to operation store)
Closes #610

feat: Add unpublished operation store option

---

pkg/versions/1_0/doctransformer/didtransformer/transformer_test.go
pkg/versions/1_0/doctransformer/doctransformer/transformer_test.go
pkg/versions/1_0/doctransformer/metadata/metadata.go
pkg/versions/1_0/doctransformer/metadata/metadata_test.go

For published operations remove duplicates and sort operations by transaction (anchoring) time.
For unpublished operations sort operations by request time.
Closes #616

chore: Organize published/unpublished operations in metadata

---

ci/azure-pipelines.yml
pkg/processor/processor_test.go
pkg/versions/1_0/operationparser/commitment.go

Don't check expiry time during commitment assembling - it will be checked later on during applying operations against anchor publishing time.
Closes #620

chore: Use batch flag during operation commitment assembling

---

pkg/dochandler/handler.go

The following functions for getting document transformation info are now public:
- GetTransformationInfoForPublished
- GetTransformationInfoForUnpublished
Closes #622

chore: Make functions for getting document transformation info public

---

pkg/api/protocol/protocol.go
pkg/batch/writer.go
pkg/batch/writer_test.go
pkg/mocks/operationhandler.gen.go
pkg/versions/1_0/txnprovider/handler.go
pkg/versions/1_0/txnprovider/handler_test.go
pkg/versions/1_0/txnprovider/provider_test.go

If there is more than one operation with same suffix in the batch return additional operations to the batch writer queue to be processed in the next batch.
Closes #624

feat: Process additional operations for suffix in the next batch

---

pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/processor/processor.go
pkg/processor/processor_test.go
pkg/versions/1_0/txnprocessor/txnprocessor.go
pkg/versions/1_0/txnprocessor/txnprocessor_test.go

Add support for multiple operations in unpublished operation store.
Closes #626

chore: Add support for multiple operations in unpublished  store

---

pkg/batch/writer.go
pkg/batch/writer_test.go

Previously, adding a new operation may need to wait for the batch to be cut if the buffer of the Go channel has been maxed out. This commit changes the behaviour such that adding a new operation does not wait on the Go channel. Instead, the queue is monitored in the background (by default, every 1 second) to see if the maximum batch size has been reached. If so, the batch is cut.

fix: Adding new operations don't wait for batch to be cut

---

pkg/mocks/metricsprovider.go
pkg/restapi/diddochandler/resolvehandler.go
pkg/restapi/diddochandler/resolvehandler_test.go
pkg/restapi/diddochandler/restapi_test.go
pkg/restapi/diddochandler/updatehandler.go
pkg/restapi/diddochandler/updatehandler_test.go
pkg/restapi/dochandler/resolvehandler.go
pkg/restapi/dochandler/resolvehandler_test.go
pkg/restapi/dochandler/updatehandler.go
pkg/restapi/dochandler/updatehandler_test.go

chore: add metrics for create and resolve rest call

---

pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/processor/processor.go
pkg/processor/processor_test.go

Allow update If create operation exists in unpublished store.
Closes #635

feat: Allow update without published create operation

---

pkg/processor/processor.go

Fixes a race condition which may occur when published operations are first retrieved, not found, and then unpublished operations are deleted before they are retrieved. In this case the DID resolve results in a 404 "not found" error.
This commit reverses the order of retrieval, i.e. first retrieve the unpublished operations and then the published ones.
closes #642

fix: Fix race condition in resolve

---

pkg/api/protocol/protocol.go
pkg/mocks/txnprocessor.gen.go
pkg/observer/observer.go
pkg/observer/observer_test.go
pkg/versions/1_0/txnprocessor/txnprocessor.go
pkg/versions/1_0/txnprocessor/txnprocessor_test.go

Change the transaction processor interface to return the number of operations that were actually processed. In the case of duplicate operations, the number processed may be zero and the caller may wish to take a different path in this case.

feat: Return the number of operations processed

---

pkg/restapi/dochandler/resolvehandler.go
pkg/restapi/dochandler/resolvehandler_test.go

Return an error if the client specifies both versionId and versionTime.
closes #651

fix: Should not be able to specify both versionId and versionTime

---

pkg/processor/processor.go
pkg/processor/processor_test.go

Fix published operations in document metadata, got broken with filtering published/unpublished operations as per versionId/versionTime.
Closes #653

fix: Fix published operations in document metadata

---

go.mod
go.sum
pkg/document/publickey.go
pkg/document/publickey_test.go
pkg/versions/1_0/doctransformer/didtransformer/transformer.go
pkg/versions/1_0/doctransformer/didtransformer/transformer_test.go

feat: add support for ed25519signature2020

---

pkg/api/protocol/protocol.go
pkg/document/resolution.go
pkg/versions/1_0/doctransformer/metadata/metadata.go
pkg/versions/1_0/doctransformer/metadata/metadata_test.go
pkg/versions/1_0/operationapplier/operationapplier.go
pkg/versions/1_0/operationapplier/operationapplier_test.go

Add created and updated to document metadata during resolution
Closes #664

feat: Add created and updated to document metadata during resolution

---

pkg/versions/1_0/doctransformer/metadata/metadata.go
pkg/versions/1_0/operationapplier/operationapplier.go
pkg/versions/1_0/operationapplier/operationapplier_test.go

Propagate "created" time for update, recover, deactivate operations.
Also, don't include "updated" if there was no update operations (e.g. create followed by deactivate)
Closes #666

chore: Fix propagating created

---

pkg/versions/1_0/doctransformer/metadata/metadata.go
pkg/versions/1_0/doctransformer/metadata/metadata_test.go

Since Sidetree resolution is processing full operations first (create, recover, deactivate) having "updated" in the resolution result for deactivate document will lead to inconsistent behaviour. If there was a 'recover' operation in the chain it will return "updated" otherwise it will be empty. Also in this case "updated" means the anchoring time of last recover and not necessarily the last update.
Closes #668

chore: Remove "updated" for deactivated document

---

pkg/versions/1_0/doctransformer/metadata/metadata.go
pkg/versions/1_0/doctransformer/metadata/metadata_test.go
pkg/versions/1_0/operationapplier/operationapplier.go

Resolution result for 'deactivated' document should return deactivate operation anchoring time in "updated" field of document metadata.
Closes #670

chore: Return deactivate operation anchoring time in "updated"

---

pkg/versions/1_0/operationparser/patchvalidator/document.go
pkg/versions/1_0/operationparser/patchvalidator/document_test.go

According to did-core service endpoint should accept:
- string (has to be valid URI)
- list of strings (each has to be valid URI)
- an object
- list of objects
Closes #674

feat: Service endpoint object should accept list of strings and list of objects

---

pkg/document/diddocument.go
pkg/versions/1_0/doctransformer/didtransformer/testdata/doc.json
pkg/versions/1_0/doctransformer/didtransformer/transformer.go
pkg/versions/1_0/doctransformer/didtransformer/transformer_test.go

Add support for alsoKnownAs during did transformation
Closes #677

chore: Add support for alsoKnownAs during did transformation

---

pkg/document/diddocument.go
pkg/document/diddocument_test.go
pkg/document/document.go
pkg/document/testdata/pk-doc.json
pkg/patch/patch.go
pkg/patch/patch_test.go
pkg/versions/1_0/doccomposer/composer.go
pkg/versions/1_0/doccomposer/composer_test.go
pkg/versions/1_0/doctransformer/didtransformer/transformer.go
pkg/versions/1_0/operationparser/patchvalidator/alsoknownas.go
pkg/versions/1_0/operationparser/patchvalidator/alsoknownas_test.go
pkg/versions/1_0/operationparser/patchvalidator/validator.go
pkg/versions/1_0/operationparser/patchvalidator/validator_test.go

Add two custom patches for adding/removing also known as URIs:
-add-also-known-as
-remove-also-known-as
Closes #679

feat: Add custom patches for also known as

---

pkg/patch/patch.go
pkg/patch/patch_test.go
pkg/versions/1_0/operationparser/patchvalidator/alsoknownas.go
pkg/versions/1_0/operationparser/patchvalidator/alsoknownas_test.go

Remove the '-' prefix from the patches.
Closes #681

chore: Rename "also known as" sidetree patch

---

pkg/dochandler/handler.go
pkg/versions/1_0/doctransformer/didtransformer/transformer.go

Fill in controller when base is present.
This will make it as per spec. Reference app fixed the issue too.
Closes #691

chore: Fill-in controller when base is present

---

pkg/patch/patch.go
pkg/patch/patch_test.go

fix: Ensure "patches" slice is alway constructed in the same order

---

pkg/batch/cutter/cutter.go
pkg/batch/cutter/cutter_test.go
pkg/batch/opqueue/memqueue.go
pkg/batch/opqueue/memqueue_test.go
pkg/batch/writer.go
pkg/batch/writer_test.go
pkg/mocks/operationqueue.gen.go

Add an error parameter to the operation queue's Nack function to provide information on why the batch failed.

chore: Add error param to operation queue, 'nack' function

---

pkg/api/operation/models.go
pkg/batch/cutter/cutter.go
pkg/dochandler/handler.go

Added two fields:
- Type: The type of operation (create, update, recover, etc.)
- Properties: An arbitrary set of properties of the operation

feat: Added Type and Properties to Operation
