.gitignore
.golangci.yml
.travis.yml
Makefile
pkg/api/api.go
scripts/check_license.sh
scripts/check_lint.sh
scripts/dependencies.sh
scripts/unit.sh

Add makefile and supporting scripts
Closes #3

chore: Add Makefile

---

go.mod
go.sum
pkg/api/batch/operation.go
pkg/api/protocol/protocol.go
pkg/batch/writer.go
pkg/batch/writer_test.go
pkg/document/document.go
pkg/document/document_test.go
pkg/document/testdata/doc.json
pkg/mocks/protocol.go
pkg/mocks/store.go
pkg/processor/processor.go
pkg/processor/processor_test.go
pkg/utils/hash.go
pkg/utils/hash_test.go

OperationProcessor will process document operations in chronological order and create final document during resolution.
It will use operation store client to retrieve all operations that are related to requested document.
Closes #10

feat: Operation Processor

---

pkg/batch/writer.go
pkg/dochandler/docvalidator/validator.go
pkg/dochandler/docvalidator/validator_test.go
pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/document/document.go
pkg/document/document_test.go
pkg/utils/doc.go
pkg/utils/doc_test.go
pkg/utils/hash.go
pkg/utils/hash_test.go

Document handler performs document operation processing and document resolution.
During operation processing it will use configured validator to validate document operation and then it will call batch writer to add it to the batch.
Document resolution is based on ID or encoded original document.
Closes #13

feat: Document Handler

---

pkg/batch/filehandler/handler.go
pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/docutil/doc.go
pkg/docutil/doc_test.go
pkg/docutil/encoder.go
pkg/docutil/encoder_test.go
pkg/docutil/hash.go
pkg/docutil/hash_test.go
pkg/mocks/cas.go
pkg/processor/processor.go
pkg/processor/processor_test.go

chore: Rename utils to docutils

---

docs/source/index.rst
docs/source/overview.rst

docs: Add Overview Document

---

README.md

Signed-off-by: talwinder.kaur <talwinder.kaur@securekey.com>

chore: Adding documentation link in readme

---

pkg/mocks/store.go
pkg/processor/processor_test.go

test: Add validation to mock store

---

pkg/api/batch/operation.go

fix: Add json tags to operation

---

pkg/observer/observer.go
pkg/observer/observer_test.go

chore: Rename SidetreeTxn fields

---

pkg/batch/writer.go
pkg/mocks/blockchain.go

chore: Add Read method for blockchain mock

---

pkg/processor/processor.go

chore: Add put method to OperationStoreClient interface

---

.golangci.yml
scripts/check_lint.sh

Signed-off-by: Rolson Quadras <rolson.quadras@securekey.com>

ci: GolangCI Lint - Update docker image source

---

pkg/dochandler/didvalidator/validator.go
pkg/document/diddocument.go
pkg/document/diddocument_test.go
pkg/document/document.go
pkg/document/document_test.go
pkg/document/testdata/doc.json

feat: Change DID context to array

---

README.md

ci: update build badge in README

---

docs/source/overview.rst

chore: Updated docs for release v0.1.1

---

go.mod
go.sum
pkg/batch/filehandler/handler.go
pkg/batch/filehandler/handler_test.go
pkg/batch/writer.go
pkg/batch/writer_test.go
pkg/observer/observer.go

chore: Remove Merkle Tree references

---

pkg/processor/processor.go
pkg/processor/processor_test.go
pkg/restapi/diddochandler/updatehandler_test.go
pkg/restapi/dochandler/updatehandler.go
pkg/restapi/dochandler/updatehandler_test.go

Return document instad of create operation when initial value is not present.
Closes #103

fix: Did Resolution

---

pkg/dochandler/didvalidator/validator.go
pkg/dochandler/didvalidator/validator_test.go
pkg/dochandler/docvalidator/validator.go
pkg/dochandler/docvalidator/validator_test.go
pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/docutil/hash.go
pkg/docutil/hash_test.go
pkg/mocks/dochandler.go
pkg/mocks/store.go
pkg/observer/observer.go
pkg/observer/observer_test.go
pkg/processor/processor.go
pkg/processor/processor_test.go
pkg/restapi/dochandler/payload.go
pkg/restapi/dochandler/payload_test.go
pkg/restapi/dochandler/resolvehandler_test.go
pkg/restapi/dochandler/updatehandler.go
pkg/restapi/dochandler/updatehandler_test.go
pkg/restapi/model/operation_type.go

Added logic for deleting document
Closes #80

feat: Delete Document

---

pkg/mocks/dochandler.go
pkg/processor/processor.go
pkg/processor/processor_test.go
pkg/restapi/dochandler/resolvehandler.go
pkg/restapi/dochandler/resolvehandler_test.go
pkg/restapi/dochandler/updatehandler_test.go

Distinguish between document not found and deleted

Distinguish between document not found and document was deleted

---

pkg/api/batch/operation.go
pkg/dochandler/didvalidator/testdata/doc.json
pkg/dochandler/didvalidator/validator.go
pkg/dochandler/didvalidator/validator_test.go
pkg/dochandler/docvalidator/validator_test.go
pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/document/diddocument_test.go
pkg/document/document.go
pkg/document/testdata/doc.json
pkg/document/testdata/missing-info.json
pkg/mocks/dochandler.go
pkg/processor/processor.go
pkg/processor/processor_test.go
pkg/restapi/diddochandler/restapi_test.go
pkg/restapi/diddochandler/updatehandler_test.go
pkg/restapi/dochandler/payload.go
pkg/restapi/dochandler/payload_test.go
pkg/restapi/dochandler/resolvehandler_test.go
pkg/restapi/dochandler/updatehandler_test.go
pkg/restapi/model/payload.go

Create payload schema has been changed in the spec. Update to the latest spec.
Closes #106

feat: Update create payload schema

---

pkg/dochandler/handler.go
pkg/dochandler/handler_test.go

If doc resolution has been done from ledger return published = true. If it has been resolved from initial-document return false.
Closes #121

feat: Add publish flag

---

pkg/docutil/hash.go
pkg/docutil/hash_test.go
pkg/mocks/protocol.go
pkg/processor/processor_test.go
pkg/restapi/diddochandler/updatehandler_test.go
pkg/restapi/dochandler/payload.go
pkg/restapi/dochandler/payload_test.go
pkg/restapi/dochandler/updatehandler_test.go

Enforce mandatory fields and their formats(check multihashes).
Closes #123

feat: Enforce mandatory fields for create

---

pkg/restapi/helper/request.go
pkg/restapi/helper/request_test.go

chore: Add update helper

---

pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/operation/create_test.go
pkg/operation/recover.go
pkg/operation/recover_test.go
pkg/processor/processor.go
pkg/processor/processor_test.go
pkg/restapi/diddochandler/updatehandler_test.go
pkg/restapi/dochandler/resolvehandler_test.go
pkg/restapi/helper/request.go
pkg/restapi/helper/request_test.go
pkg/restapi/model/operation_type.go
pkg/restapi/model/request.go

Recover document

---

pkg/dochandler/handler_test.go
pkg/operation/update.go
pkg/operation/update_test.go
pkg/restapi/dochandler/updatehandler_test.go
pkg/restapi/helper/request.go
pkg/restapi/helper/request_test.go
pkg/restapi/model/request.go

Handle ietf-json-patch
Closes #156

feat: Add ietf-json-patch

---

pkg/restapi/dochandler/updatehandler_test.go
pkg/restapi/helper/request.go

missed changing it originally
Closes #162

fix: reveal value type for revoke

---

pkg/composer/composer.go
pkg/composer/composer_test.go
pkg/dochandler/handler_test.go
pkg/document/diddocument.go
pkg/document/document.go
pkg/document/document_test.go
pkg/document/publickey.go
pkg/document/publickey_test.go
pkg/mocks/dochandler.go
pkg/operation/create_test.go
pkg/operation/recover_test.go
pkg/operation/update_test.go
pkg/patch/patch.go
pkg/patch/patch_test.go
pkg/processor/processor_test.go
pkg/restapi/diddochandler/updatehandler_test.go
pkg/restapi/dochandler/resolvehandler_test.go
pkg/restapi/dochandler/updatehandler_test.go
pkg/restapi/helper/request.go
pkg/restapi/helper/request_test.go

Add patches for adding and removing public keys
Also, add basic validation to replace and json patches.
Closes #155

feat: add/remove public keys patches

---

pkg/composer/composer.go
pkg/composer/composer_test.go
pkg/document/service.go
pkg/document/service_test.go
pkg/patch/patch.go
pkg/patch/patch_test.go

Implement add/remove service endpoints patches
Closes #171

feat: Add/remove service endpoints

---

pkg/operation/recover.go
pkg/operation/recover_test.go
pkg/operation/revoke.go
pkg/operation/revoke_test.go
pkg/operation/update.go
pkg/processor/processor_test.go
pkg/restapi/helper/request.go
pkg/restapi/helper/request_test.go
pkg/restapi/model/request.go

Review all operations that require signing and make sure that signed data is constructed as per spec and using correct encoding.
Closes #173

chore: Prepare data for signing

---

pkg/api/batch/operation.go
pkg/mocks/dochandler.go
pkg/operation/deactivate.go
pkg/operation/deactivate_test.go
pkg/processor/operationfilter.go
pkg/processor/operationfilter_test.go
pkg/processor/processor.go
pkg/processor/processor_test.go
pkg/restapi/dochandler/resolvehandler.go
pkg/restapi/dochandler/resolvehandler_test.go
pkg/restapi/dochandler/updatehandler.go
pkg/restapi/dochandler/updatehandler_test.go
pkg/restapi/helper/request.go
pkg/restapi/helper/request_test.go
pkg/restapi/model/request.go
pkg/restapi/model/types.go

Rename revoke to deactivate
Closes #185

chore: Rename revoke to deactivate

---

pkg/processor/processor.go
pkg/processor/processor_test.go

fix: Add checks for nil in signed data

---

pkg/dochandler/didvalidator/validator.go
pkg/document/diddocument.go
pkg/document/publickey.go
pkg/document/validator.go
pkg/document/validator_test.go

Remove key usage from external document
closes #210

fix: Usage should not be in external document

---

pkg/api/batch/operation.go
pkg/batch/writer_test.go
pkg/dochandler/didvalidator/validator.go
pkg/dochandler/didvalidator/validator_test.go
pkg/dochandler/docvalidator/validator.go
pkg/dochandler/docvalidator/validator_test.go
pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/mocks/dochandler.go
pkg/operation/create.go
pkg/operation/create_test.go
pkg/operation/deactivate.go
pkg/operation/deactivate_test.go
pkg/operation/recover.go
pkg/operation/recover_test.go
pkg/operation/update.go
pkg/operation/update_test.go
pkg/processor/processor.go
pkg/processor/processor_test.go
pkg/restapi/diddochandler/updatehandler_test.go
pkg/restapi/dochandler/resolvehandler_test.go
pkg/restapi/dochandler/updatehandler_test.go
pkg/restapi/helper/request.go
pkg/restapi/helper/request_test.go
pkg/restapi/model/request.go

Updated JSON tags, renamed model and vars to match tags: patch data to delta, did unique suffix to did suffix etc.
Closes #189

feat: Match JSON tags from document

---

pkg/dochandler/didvalidator/testdata/doc.json
pkg/dochandler/didvalidator/validator.go
pkg/dochandler/didvalidator/validator_test.go
pkg/document/diddocument.go
pkg/document/diddocument_test.go
pkg/document/validator.go
pkg/document/validator_test.go

feat: Support agreement key usage

---

pkg/composer/composer.go
pkg/composer/composer_test.go
pkg/dochandler/didvalidator/testdata/doc.json
pkg/dochandler/didvalidator/validator.go
pkg/dochandler/didvalidator/validator_test.go
pkg/dochandler/docvalidator/validator.go
pkg/dochandler/docvalidator/validator_test.go
pkg/dochandler/handler_test.go
pkg/document/diddocument.go
pkg/document/diddocument_test.go
pkg/document/document.go
pkg/document/document_test.go
pkg/document/publickey.go
pkg/document/publickey_test.go
pkg/document/service.go
pkg/document/testdata/doc.json
pkg/document/validator.go
pkg/document/validator_test.go
pkg/operation/create_test.go
pkg/patch/patch.go
pkg/patch/patch_test.go
pkg/processor/processor.go
pkg/processor/processor_test.go
pkg/restapi/diddochandler/updatehandler_test.go
pkg/restapi/dochandler/updatehandler_test.go

-- Distinguish between internal and external public key model
-- Add validation for public keys, modify tests for valid input
-- Rename patch key names
-- validate paches before applying 
Closes #222

Change publicKeyJwk to jwk in add public keys and initial document

---

pkg/document/validator.go

chore: Allow X25519KeyAgreementKey2019

---

pkg/document/validator.go
pkg/document/validator_test.go

Remove validation of Y since Ed25519 doesn't have Y
Closes #231

JWK - Remove validation of Y

---

pkg/dochandler/didvalidator/validator.go
pkg/dochandler/didvalidator/validator_test.go
pkg/document/diddocument.go
pkg/document/service.go

fix: Wrong label for service endpoint

---

pkg/document/validator.go
pkg/document/validator_test.go

enables each usage to define its own list of allowed types.
closes: #233

feat: fine-grained usage validation

---

pkg/internal/request/method.go
pkg/internal/request/method_test.go

Remove network from method initial state parameter
Closes #247

fix: Remove network from method initial state parameter

---

pkg/dochandler/handler_test.go
pkg/jws/header_test.go
pkg/jws/jwk.go
pkg/jws/jwk_test.go
pkg/operation/create.go
pkg/operation/create_test.go
pkg/operation/deactivate.go
pkg/operation/deactivate_test.go
pkg/operation/recover.go
pkg/operation/recover_test.go
pkg/operation/update.go
pkg/operation/update_test.go
pkg/restapi/diddochandler/updatehandler_test.go
pkg/restapi/helper/request.go

Additional request validations for:
- create
- update
- recover
- deactivate
Also, more validation for helper
Closes #201

chore: Request validation at server side

---

pkg/dochandler/handler_test.go
pkg/internal/request/method.go
pkg/internal/request/method_test.go
pkg/operation/create_test.go
pkg/restapi/dochandler/resolvehandler_test.go

Spec changed the order
Closes #266

chore: Fix the order of params in initial state

---

pkg/dochandler/didvalidator/testdata/doc.json
pkg/dochandler/didvalidator/validator.go
pkg/dochandler/didvalidator/validator_test.go
pkg/document/diddocument.go
pkg/document/diddocument_test.go
pkg/document/validator.go
pkg/document/validator_test.go

feat: Support capability key usage

---

pkg/dochandler/didvalidator/testdata/doc.json
pkg/dochandler/didvalidator/validator.go
pkg/dochandler/didvalidator/validator_test.go
pkg/document/diddocument_test.go
pkg/document/service.go
pkg/document/testdata/doc.json
pkg/document/validator.go
pkg/document/validator_test.go
pkg/patch/patch.go
pkg/patch/patch_test.go
pkg/restapi/common/httputil.go
pkg/restapi/dochandler/resolvehandler.go
pkg/restapi/dochandler/updatehandler.go

Add validation of services (document + patches)
Add validation of public key length
Also, added more top level error logging
Closes #202

feat: Add validation of services

---

pkg/document/validator.go
pkg/document/validator_test.go

chore: Remove pub key ID validation

---

pkg/document/validator.go
pkg/document/validator_test.go

Revert to original public key ID validation
Closes #278

chore: Revert to original public key ID validation

---

pkg/batch/cutter/cutter.go
pkg/batch/writer.go
pkg/dochandler/handler.go

chore: Add info logging to batch writer

---

pkg/api/batch/operation.go
pkg/operation/create.go
pkg/operation/create_test.go
pkg/operation/deactivate.go
pkg/operation/operation.go
pkg/operation/recover.go
pkg/operation/update.go
pkg/operation/update_test.go
pkg/processor/processor.go
pkg/processor/processor_test.go
pkg/restapi/helper/recover.go
pkg/restapi/helper/update.go
pkg/restapi/model/request.go

-- move reveal value to signed data
-- consolidate signed data parsing
Closes #299

chore: Move reveal values to signed data

---

go.sum
pkg/batch/writer.go
pkg/batch/writer_test.go
pkg/dochandler/handler_test.go
pkg/docutil/doc.go
pkg/docutil/doc_test.go
pkg/mocks/blockchain.go
pkg/observer/observer.go
pkg/observer/observer_test.go

Batch Writer:
-- use transaction handler to create batch files from batch operations
Observer:
-- use transaction handler to parse batch operations from batch files 
Closes #287 #297 #165 

Create Chunk/Map/Anchor File

---

pkg/api/txn/sidetree.go
pkg/batch/writer_test.go
pkg/mocks/blockchain.go
pkg/observer/observer.go
pkg/observer/observer_test.go
pkg/txnhandler/anchordata.go
pkg/txnhandler/anchordata_test.go
pkg/txnhandler/handler.go
pkg/txnhandler/handler_test.go
pkg/txnhandler/provider.go
pkg/txnhandler/provider_test.go

Record anchor string (num of transactions + anchor address) on blockchain.
Closes #293

chore: Create Anchor String

---

pkg/api/txn/sidetree.go
pkg/batch/writer.go
pkg/batch/writer_test.go
pkg/mocks/blockchain.go
pkg/txnhandler/models/anchor.go
pkg/txnhandler/models/map.go
pkg/txnhandler/provider.go
pkg/txnhandler/provider_test.go

-- add namespace as part of Sidetree transaction
-- remove namespace from batch models
Closes #314

chore: Add namespace to Sidetree transaction

---

pkg/compression/gzip/algorithm.go
pkg/compression/gzip/algorithm_test.go
pkg/compression/registry.go
pkg/compression/registry_test.go

Add compression registry with gzip algorithm implementation
Closes #316

feat: Add compression registry

---

pkg/composer/composer_test.go
pkg/dochandler/didvalidator/testdata/doc.json
pkg/dochandler/didvalidator/validator.go
pkg/dochandler/didvalidator/validator_test.go
pkg/dochandler/docvalidator/validator_test.go
pkg/dochandler/handler_test.go
pkg/document/diddocument_test.go
pkg/document/publickey.go
pkg/document/publickey_test.go
pkg/document/testdata/doc.json
pkg/document/validator.go
pkg/document/validator_test.go
pkg/operation/create_test.go
pkg/patch/patch_test.go
pkg/processor/processor_test.go
pkg/restapi/diddochandler/updatehandler_test.go
pkg/restapi/dochandler/updatehandler_test.go

Spec change: rename usage to purpose for public keys
Closes #328

chore: Rename usage to purpose for public keys

---

pkg/document/diddocument_test.go
pkg/document/testdata/doc.json
pkg/document/validator.go
pkg/document/validator_test.go

Signed-off-by: George Aristy <george.aristy@securekey.com>

fix: allow didcomm service 'priority' attribute

---

go.mod
go.sum
pkg/batch/cutter/cutter.go
pkg/observer/observer.go
pkg/restapi/common/handler.go
pkg/restapi/dochandler/resolvehandler.go

I missed the logrus loggers in my last PR.
Signed-off-by: Derek Trider <Derek.Trider@securekey.com>

feat: Switch logrus logging to edge-core logging

---

pkg/processor/processor.go
pkg/processor/processor_test.go

Create operation hash map (calculate operation commitment value) during resolution and use it to determine next operation to be applied.
Closes #326

feat: Operation Hash Map

---

pkg/api/batch/operation.go
pkg/dochandler/didvalidator/validator.go
pkg/dochandler/didvalidator/validator_test.go
pkg/dochandler/docvalidator/validator.go
pkg/dochandler/docvalidator/validator_test.go
pkg/dochandler/handler_test.go
pkg/mocks/store.go
pkg/observer/noopoperationfilter.go
pkg/observer/noopoperationfilter_test.go
pkg/observer/observer.go
pkg/observer/observer_test.go
pkg/processor/operationfilter.go
pkg/processor/operationfilter_test.go
pkg/processor/processor.go
pkg/processor/processor_test.go
pkg/txnhandler/provider.go

Create the smallest subset of operation data that will be stored into operation store as anchored operation.
Closes #344

chore: Create Anchored Operation model

---

pkg/document/validator.go
pkg/document/validator_test.go

Applies to public key ids and service ids
Closes #352

chore: Update ID limit to 50

---

pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/document/resolution.go
pkg/internal/request/method.go
pkg/internal/request/method_test.go
pkg/mocks/validator.go

During resolution with initial state add initial state to method metadata
Closes #358

chore: add initial state to method metadata

---

pkg/composer/composer_test.go
pkg/dochandler/didvalidator/testdata/doc.json
pkg/dochandler/didvalidator/validator_test.go
pkg/dochandler/docvalidator/validator_test.go
pkg/dochandler/handler_test.go
pkg/document/diddocument_test.go
pkg/document/testdata/doc.json
pkg/document/validator.go
pkg/document/validator_test.go
pkg/operation/create_test.go
pkg/patch/patch_test.go
pkg/processor/processor_test.go
pkg/restapi/diddochandler/updatehandler_test.go

Add support for JsonWebKey2020
Closes #359

chore: Add JsonWebKey2020

---

pkg/dochandler/didvalidator/validator.go
pkg/document/validator.go
pkg/document/validator_test.go

Remove validation of optional service properties
Closes #335

chore: remove validation of optional service properties

---

pkg/dochandler/didvalidator/validator.go
pkg/operation/recover.go
pkg/txnhandler/provider.go

Remove TODO: Add Sidetree context
Also added issue numbers to leftover TODOs
Closes #379

chore: Remove TODO: Add Sidetree context

---

pkg/dochandler/didvalidator/validator.go
pkg/dochandler/didvalidator/validator_test.go

Add ability to configure method contexts.
Main context is still hard-coded, additional method contexts will be added if that option is supplied to validator.
Closes #382

chore: configure method context

---

pkg/txnhandler/handler_test.go
pkg/txnhandler/provider.go
pkg/txnhandler/provider_test.go

Includes map file which contains update operations
Closes #391

chore: Reject anchor file with multiple operations with same suffix

---

pkg/api/protocol/protocol.go
pkg/batch/cutter/cutter.go
pkg/batch/cutter/cutter_test.go
pkg/batch/writer.go
pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/mocks/protocol.go
pkg/restapi/dochandler/updatehandler.go
pkg/txnhandler/handler.go
pkg/txnhandler/handler_test.go
pkg/txnhandler/provider.go

chore: Return error from protocol client Current()

---

pkg/processor/processor.go

Add more logging in case of commit mismatch - even though this is not an error it might be useful for troubleshooting in integration environments
Closes #400

chore: Additional logging related to commitment when applying operations

---

pkg/processor/processor.go
pkg/processor/processor_test.go

For recovery operation advance recovery commitment in case of specific failures:
- delta doesn't match delta hash
- delta is invalid
- apply patches fails
Closes #388

feat: recover - advance commitment in case of some failures

---

pkg/processor/processor.go
pkg/processor/processor_test.go

For create operation advance recovery/update commitments as soon as they become available. Here is the list of specific failures:
- delta doesn't match delta hash
- delta is invalid
- apply patches fails
Closes #404

chore: create - advance commitments in case of some failures

---

pkg/api/protocol/protocol.go
pkg/dochandler/handler_test.go
pkg/mocks/protocol.go
pkg/processor/processor.go
pkg/processor/processor_test.go
pkg/versions/0_1/operationapplier/operationapplier.go
pkg/versions/0_1/operationapplier/operationapplier_test.go

Resolve next operation when hashing/multihashing algorithm changes in between operations
Closes #412

chore: Resolve next operation when hashing/multihashing algorithm changes

---

pkg/api/protocol/protocol.go

chore: Added JSON annotations to protocol parameters

---

pkg/api/protocol/protocol.go
pkg/dochandler/handler_test.go
pkg/mocks/protocol.go
pkg/processor/processor_test.go
pkg/versions/0_1/operationapplier/operationapplier_test.go
pkg/versions/0_1/operationparser/create.go
pkg/versions/0_1/operationparser/create_test.go
pkg/versions/0_1/operationparser/operation_test.go
pkg/versions/0_1/operationparser/recover_test.go
pkg/versions/0_1/operationparser/update_test.go

Replace enable_replace_patch parameter with generic parameter for enabling patches
Closes #423 

chore: generic parameter for enabling patches

---

pkg/api/protocol/protocol.go
pkg/docutil/hash.go
pkg/docutil/hash_test.go
pkg/mocks/protocol.go
pkg/versions/0_1/client/create.go
pkg/versions/0_1/operationapplier/operationapplier_test.go
pkg/versions/0_1/operationparser/create.go
pkg/versions/0_1/operationparser/recover.go
pkg/versions/0_1/operationparser/update.go
pkg/versions/0_1/operationparser/update_test.go
pkg/versions/0_1/txnprovider/models/coreproof.go
pkg/versions/0_1/txnprovider/models/provisionalproof.go
pkg/versions/0_1/txnprovider/models/signed.go
pkg/versions/0_1/txnprovider/provider.go
pkg/versions/0_1/txnprovider/provider_test.go

Retrieve and validate proof files against new protocol parameter.
Also, renamed IsComputedUsingHashAlgorithm to IsComputedUsingMultihashAlgorithm
Closes #464

chore: Retrieve and validate proof files

---

pkg/versions/0_1/txnprovider/provider.go
pkg/versions/0_1/txnprovider/provider_test.go

Add validation of batch file operation counts.
Also, optimized code so there is no need to handle "deactivate only" operations separately.
Closes #473

chore: validate batch file counts

---

pkg/versions/0_1/model/operation.go
pkg/versions/0_1/operationparser/deactivate.go
pkg/versions/0_1/operationparser/deactivate_test.go
pkg/versions/0_1/operationparser/recover.go
pkg/versions/0_1/operationparser/recover_test.go
pkg/versions/0_1/operationparser/update.go
pkg/versions/0_1/operationparser/update_test.go
pkg/versions/0_1/txnprovider/models/coreindex_test.go
pkg/versions/0_1/txnprovider/models/provisionalindex_test.go
pkg/versions/0_1/txnprovider/provider.go
pkg/versions/0_1/txnprovider/provider_test.go

Populate reveal value in core index file
Closes #480

chore: Populate reveal value in core index

---

pkg/batch/writer.go
pkg/batch/writer_test.go
pkg/mocks/blockchain.go
pkg/versions/0_1/txnprocessor/txnprocessor_test.go
pkg/versions/0_1/txnprovider/anchordata.go
pkg/versions/0_1/txnprovider/anchordata_test.go
pkg/versions/0_1/txnprovider/handler.go
pkg/versions/0_1/txnprovider/handler_test.go
pkg/versions/0_1/txnprovider/provider.go
pkg/versions/0_1/txnprovider/provider_test.go

For AnchorString rename AnchorAddress to CoreIndexFileURI
Also, added one test for missing core provisional URI
Closes #483

chore: rename AnchorAddress to CoreIndexFileURI

---

pkg/versions/0_1/operationparser/recover.go
pkg/versions/0_1/txnprovider/provider.go
pkg/versions/0_1/txnprovider/provider_test.go

- change format of reveal value as per reference app
- additional batch file validations
Closes #485

chore: Additional batch file validations

---

go.mod
go.sum
pkg/versions/0_1/operationparser/commitment.go
pkg/versions/0_1/operationparser/create.go
pkg/versions/0_1/operationparser/deactivate.go
pkg/versions/0_1/operationparser/operation.go
pkg/versions/0_1/operationparser/recover.go
pkg/versions/0_1/operationparser/update.go
pkg/versions/0_1/txnprovider/handler.go
pkg/versions/0_1/txnprovider/handler_test.go
pkg/versions/0_1/txnprovider/provider.go

Even though pruning/checkpoint requirements are currently not mentioned in the official spec, reference application has few comments and some code related to future requirements.
This code is to align interfaces/code with anticipated pruning/checkpoint requirements,
Closes #500

chore: Align interfaces/code with anticipated pruning requirements

---

pkg/api/protocol/protocol.go
pkg/mocks/protocol.go
pkg/processor/processor_test.go
pkg/versions/0_1/operationapplier/operationapplier_test.go
pkg/versions/0_1/operationparser/deactivate_test.go
pkg/versions/0_1/operationparser/operation_test.go
pkg/versions/0_1/operationparser/recover.go
pkg/versions/0_1/operationparser/recover_test.go
pkg/versions/0_1/operationparser/update_test.go
pkg/versions/0_1/txnprovider/provider_test.go

This one never made it to protocol spec even though it was discussed during weekly.
Closes #523

chore: remove max proof parameter from protocol

---

pkg/versions/0_1/operationparser/deactivate.go
pkg/versions/0_1/operationparser/deactivate_test.go
pkg/versions/0_1/operationparser/recover.go
pkg/versions/0_1/operationparser/recover_test.go
pkg/versions/0_1/operationparser/update.go
pkg/versions/0_1/operationparser/update_test.go

Add validation for reveal value
Closes #525

chore: add validation for reveal value

---

pkg/api/operation/models.go
pkg/api/txn/sidetree.go

Add reference to sidetree txn and anchored operation
Closes #541

chore: add reference to sidetree txn

---

pkg/api/protocol/protocol.go
pkg/dochandler/handler.go
pkg/dochandler/handler_test.go
pkg/restapi/dochandler/resolvehandler.go
pkg/versions/0_1/operationapplier/operationapplier.go
pkg/versions/0_1/operationparser/method.go

Add reference to canonical id
Closes #543

chore: add reference to canonical id

---

pkg/versions/0_1/operationapplier/operationapplier.go
pkg/versions/0_1/operationapplier/operationapplier_test.go

During resolution, validate anchor from and anchor until against anchoring time (in operation applier).
Closes #554

chore: Validate anchor from and until during operation resolution

---

pkg/api/protocol/protocol.go
pkg/jws/jwk.go
pkg/mocks/protocol.go
pkg/versions/0_1/operationapplier/operationapplier_test.go
pkg/versions/0_1/operationparser/deactivate.go
pkg/versions/0_1/operationparser/recover.go
pkg/versions/0_1/operationparser/recover_test.go
pkg/versions/0_1/operationparser/update.go

This will allow for re-using keys for operation commitments.
Closes #558

feat: Add nonce to JWK

---

pkg/versions/1_0/operationparser/patchvalidator/document.go

Add Bls12381G2Key2020 key
Closes #566

chore: Add Bls12381G2Key2020 key

---

pkg/api/operation/models.go
pkg/api/protocol/protocol.go
pkg/document/resolution.go
pkg/versions/1_0/doctransformer/metadata.go
pkg/versions/1_0/doctransformer/metadata_test.go
pkg/versions/1_0/operationapplier/operationapplier.go
pkg/versions/1_0/txnprovider/handler.go

Add anchor origin to method metadata
Closes #571

feat: Add anchor origin to method metadata

---

pkg/dochandler/handler.go
pkg/dochandler/handler_test.go

If label/domain is specified for document handler create an equivalent ID with "label:domain" hint for long-form DIDs.
Also, provide label as document handler option.
Closes #584

chore: Add support for label/domain hint in long-form DIDs

---

pkg/versions/1_0/operationparser/patchvalidator/document.go

Remove references to JwsVerificationKey2020
Closes #585

chore: Remove references to JwsVerificationKey2020

---

pkg/api/operation/models.go
pkg/versions/1_0/model/operation.go
pkg/versions/1_0/model/util.go
pkg/versions/1_0/txnprovider/provider.go
pkg/versions/1_0/txnprovider/provider_test.go

Add anchor origin to anchored operation model
Closes #589

chore: Add anchor origin to anchored operation model

---

pkg/batch/writer.go

chore: Remove unnecessary debug logs in batch writer

---

pkg/api/protocol/protocol.go
pkg/batch/writer.go
pkg/mocks/blockchain.go
pkg/mocks/operationhandler.gen.go
pkg/versions/1_0/txnprovider/handler.go
pkg/versions/1_0/txnprovider/handler_test.go
pkg/versions/1_0/txnprovider/provider_test.go

Add artifacts (list of batch files) to operation handler PrepareTxnFiles
Closes #601

chore: Add artifacts to operation handler PrepareTxnFiles

---

pkg/dochandler/handler.go
pkg/dochandler/handler_test.go

Switch the order of interim label and domain.
Closes #603

chore: Switch the order of interim label and domain.

---

go.mod
go.sum

Signed-off-by: Andriy Holovko <andriy.holovko@gmail.com>

chore: update edge-core dependency

---

pkg/versions/1_0/doctransformer/didtransformer/transformer.go
pkg/versions/1_0/doctransformer/didtransformer/transformer_test.go
pkg/versions/1_0/operationparser/patchvalidator/document.go
pkg/versions/1_0/operationparser/patchvalidator/document_test.go

Signed-off-by: Filip Burlacu <filip.burlacu@securekey.com>

fix: allow doc public keys to use base58 key if jwk not available

---

pkg/processor/processor.go

chore: change log msg from info to debug

---

pkg/versions/1_0/txnprovider/provider.go

chore: Add logging for alternate CAS sources

---

pkg/document/resolution.go
pkg/document/resolution_test.go
pkg/processor/processor.go
pkg/processor/processor_test.go
pkg/restapi/dochandler/resolvehandler.go
pkg/restapi/dochandler/resolvehandler_test.go

Resolve DID based on versionTime
Closes #647

feat: Resolve DID based on versionTime

---

pkg/versions/1_0/operationparser/patchvalidator/document.go

chore: support 	ed25519VerificationKey2020

---

.github/workflows/build.yml

chore: fix upload code cov

---

.github/workflows/build.yml
.github/workflows/sonar.yml

chore: provide SONAR_TOKEN

---

.github/workflows/sonar.yml

chore: use SONAR_TOKEN 

---

.github/workflows/sonar.yml

chore: remove sonar build name

---

.github/workflows/sonar.yml

chore: change sonar build name

---

.github/workflows/sonar.yml

chore: fix sonar name

---

pkg/batch/writer_test.go
pkg/dochandler/handler_test.go
pkg/mocks/metricsprovider.go
pkg/versions/1_0/txnprovider/handler.go
pkg/versions/1_0/txnprovider/handler_test.go
pkg/versions/1_0/txnprovider/provider_test.go

chore: Add CAS write size metric
